// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc319;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.CANTalon;
import edu.wpi.first.wpilibj.AnalogInput;
import edu.wpi.first.wpilibj.Compressor;
import edu.wpi.first.wpilibj.DoubleSolenoid;
import edu.wpi.first.wpilibj.RobotDrive;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static DoubleSolenoid driveTrainshifter;
    public static CANTalon driveTrainleftDriveLead;
    public static CANTalon driveTrainleftDriveFollow;
    public static CANTalon driveTrainrightDriveLead;
    public static CANTalon driveTrainrightDriveFollow;
    public static RobotDrive driveTraindriveTrain;
    public static Compressor compressorcompressor;
    public static AnalogInput compressorpressureSensor;

    public static void init() {
        driveTrainshifter = new DoubleSolenoid(0, 0, 1);
        LiveWindow.addActuator("driveTrain", "shifter", driveTrainshifter);
        
        driveTrainleftDriveLead = new CANTalon(0);
        LiveWindow.addActuator("driveTrain", "leftDriveLead", driveTrainleftDriveLead);
        
        driveTrainleftDriveFollow = new CANTalon(3);
        LiveWindow.addActuator("driveTrain", "leftDriveFollow", driveTrainleftDriveFollow);
        
        driveTrainrightDriveLead = new CANTalon(1);
        LiveWindow.addActuator("driveTrain", "rightDriveLead", driveTrainrightDriveLead);
        
        driveTrainrightDriveFollow = new CANTalon(2);
        LiveWindow.addActuator("driveTrain", "rightDriveFollow", driveTrainrightDriveFollow);
        
        driveTraindriveTrain = new RobotDrive(driveTrainleftDriveLead, driveTrainrightDriveLead);
        
        driveTraindriveTrain.setSafetyEnabled(true);
        driveTraindriveTrain.setExpiration(0.1);
        driveTraindriveTrain.setSensitivity(0.5);
        driveTraindriveTrain.setMaxOutput(1.0);

    }
}
